server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque_upb
spring.datasource.username=biblio_user
spring.datasource.password=biblio2024
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=bibliotheque-upb